export const ACTION = {
    SIGN_IN: "SIGN_IN",
    SIGN_OUT: "SIGN_OUT",
    CAN_EDIT: "CAN_EDIT",
    CHANGE_PASSWORD: "CHANGE_PASSWORD",
    CHANGE_VISIBILITY: "CHANGE_VISIBILITY",
    CHANGE_NAME: "CHANGE_NAME",
    CHOOSE_PROJECT: "CHANGE_PROJECT",
    CHOOSE_USER: "CHOOSE_USER",
    UPDATE_PROJECTS: "UPDATE_PROJECTS",
    UPDATE_USERS: "UPDATE_USERS",
    CLEAR_REDUCER: "CLEAR_REDUCER",
    CLEAR_PROJECT: "CLEAR_PROJECT",
}
