export const ACTION = {
    SIGN_IN: "SIGN_IN",
    SIGN_OUT: "SIGN_OUT",
    CHANGE_PASSWORD: "CHANGE_PASSWORD",
    CHANGE_VISIBILITY: "CHANGE_VISIBILITY",
    CHANGE_NAME: "CHANGE_NAME",
    CHOOSE_PROJECT: "CHANGE_PROJECT",
    CHOOSE_USER: "CHOOSE_USER",
    UPDATE_ONLINE_PROJECTS: "UPDATE_ONLINE_PROJECTS",
    UPDATE_OFFLINE_PROJECTS: "UPDATE_OFFLINE_PROJECTS",
    UPDATE_ACTIVE_USERS: "UPDATE_ACTIVE_USERS",
    UPDATE_CONTACTS: "UPDATE_CONTACTS",
    CLEAR_PROJECTS: "CLEAR_PROJECTS",
}
