export const ACTION = {
  SIGN_IN: "SIGN_IN",
  SIGN_OUT: "SIGN_OUT",
  CHANGE_VISIBILITY: "CHANGE_VISIBILITY",
  CHOOSE_PROJECT: "CHANGE_PROJECT",
  UPDATE_ONLINE_PROJECTS: "UPDATE_ONLINE_PROJECTS",
  UPDATE_OFFLINE_PROJECTS: "UPDATE_OFFLINE_PROJECTS",
  UPDATE_ACTIVE_USERS: "UPDATE_ACTIVE_USERS",
  UPDATE_INACTIVE_USERS: "UPDATE_INACTIVE_USERS"
}
